"""End-to-end byte-level generation driver for SPRL-v2.

Reference implementation that runs the full pipeline:
  bytes → patcher → byte encoder → SPRLv2 → byte LM head → sampler → next byte.

This is the *simple* (non-cached) path: each generation step re-runs the
patcher and encoder over the entire prompt+generated bytes so far. It is
correct and deterministic but quadratic in the generated length; production
should wire the MLA KVCache in `kv_cache.py` to avoid re-encoding the prefix.

The driver exposes a TTT-mode hook: when `ttt=True` and the model has a
KalmanInfoMemory, a `TestTimeKalmanState` is maintained across steps.
"""

from __future__ import annotations

from typing import Optional

import torch
from torch import Tensor

from sprl.inference.sampler import byte_sampler


@torch.no_grad()
def _patches_from_bytes(model, byte_tensor: Tensor) -> Tensor:
    """Run patcher + byte encoder, returning [1, S_patches, d_model].

    `byte_tensor` is [1, T] of int byte ids.
    """
    plans = model.patcher.plan(byte_tensor)
    plan = plans[0]
    max_pb = model.cfg.patcher.max_patch_bytes
    n = plan.n_patches
    patch_bytes = torch.full(
        (n, max_pb), 256, dtype=torch.long, device=byte_tensor.device
    )
    lengths = torch.zeros(n, dtype=torch.long, device=byte_tensor.device)
    for i, (s, e) in enumerate(zip(plan.starts, plan.ends)):
        L = e - s
        patch_bytes[i, :L] = byte_tensor[0, s:e]
        lengths[i] = L
    patch_emb = model.byte_encoder(patch_bytes, lengths)  # [n, d_model]
    return patch_emb.unsqueeze(0)  # [1, n, d_model]


@torch.no_grad()
def generate(
    model,
    prompt_bytes: bytes,
    n_new: int,
    temperature: float = 1.0,
    top_p: float = 0.95,
    top_k: Optional[int] = None,
    generator: Optional[torch.Generator] = None,
    ttt: bool = False,
    device: torch.device | str = "cpu",
    eot_byte: Optional[int] = None,
) -> bytes:
    """Generate `n_new` bytes by autoregressive sampling.

    Args:
      model: an SPRLv2 instance (must have `patcher` and `byte_encoder`).
      prompt_bytes: prompt as a byte string.
      n_new: how many bytes to generate.
      temperature, top_p, top_k: sampler knobs.
      generator: torch.Generator for determinism.
      ttt: enable test-time updates of the Kalman memory (Bet A only).
      eot_byte: optional byte that ends generation early.
    """
    model.eval()
    dev = torch.device(device)
    if not model.cfg.patcher.enabled:
        raise RuntimeError("generate() requires patcher.enabled=True")

    bytes_so_far = bytearray(prompt_bytes)

    ttt_state = None
    if ttt and getattr(model, "kalman", None) is not None:
        from sprl.memory.ttt_mode import TestTimeKalmanState

        ttt_state = TestTimeKalmanState()

    for _ in range(n_new):
        byte_tensor = torch.tensor(
            [list(bytes_so_far)], dtype=torch.long, device=dev
        )
        patch_emb = _patches_from_bytes(model, byte_tensor)
        if ttt_state is not None and patch_emb.shape[1] > 0:
            from sprl.memory.ttt_mode import update as ttt_update_step

            ttt_update_step(model.kalman, ttt_state, patch_emb[:, -1])
        out = model.forward_from_patches(patch_emb)
        # byte_logits shape: [B, S_patches, max_patch_bytes, vocab].
        last_patch_logits = out.byte_logits[0, -1]  # [max_patch_bytes, vocab]
        # Position 0 of the next (incipient) byte slot.
        next_logits = last_patch_logits[0]
        next_byte = byte_sampler(
            next_logits,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            generator=generator,
        )
        bytes_so_far.append(next_byte)
        if eot_byte is not None and next_byte == eot_byte:
            break

    return bytes(bytes_so_far[len(prompt_bytes):])
