"""Speculative decoding via the MTP (multi-token prediction) head.

Standard speculative-decoding scheme (Leviathan et al. 2023):

  draft model proposes `mtp_depth` tokens with probabilities q_1..q_d;
  target model verifies in parallel with probabilities p_1..p_d;
  accept token i with probability min(1, p_i(x_i) / q_i(x_i));
  on rejection at step k, sample x_k' ∝ max(0, p_k − q_k); discard the rest.

Our draft model is the SPRLv2 MTP head: a depth-D auxiliary stack producing
next-D byte logits from the same hidden state as the main head. The target
model is the main byte LM head applied at the next forward pass.

Returns the generated byte string and the empirical acceptance rate.
"""

from __future__ import annotations

from typing import Optional, Tuple

import torch
from torch import Tensor

from sprl.inference.generate import _patches_from_bytes
from sprl.inference.sampler import byte_sampler


@torch.no_grad()
def speculative_decode(
    model,
    prompt_bytes: bytes,
    n_new: int,
    mtp_depth: int = 2,
    temperature: float = 1.0,
    top_p: float = 0.95,
    generator: Optional[torch.Generator] = None,
    device: torch.device | str = "cpu",
) -> Tuple[bytes, float]:
    """Generate `n_new` bytes via MTP-driven speculative decoding.

    Returns (generated_bytes, acceptance_rate). The acceptance rate is
    proposals-accepted / proposals-issued.
    """
    if model.mtp is None:
        raise RuntimeError("speculative_decode requires model.mtp to be enabled")
    model.eval()
    dev = torch.device(device)

    bytes_so_far = bytearray(prompt_bytes)
    mtp_depth = min(mtp_depth, model.mtp.depth)

    n_proposed = 0
    n_accepted = 0

    while len(bytes_so_far) - len(prompt_bytes) < n_new:
        byte_tensor = torch.tensor(
            [list(bytes_so_far)], dtype=torch.long, device=dev
        )
        patch_emb = _patches_from_bytes(model, byte_tensor)
        future_dummy = torch.zeros(
            patch_emb.shape[0], patch_emb.shape[1], model.mtp.depth,
            dtype=torch.long, device=dev,
        )
        out = model.forward_from_patches(patch_emb, future_targets=future_dummy)

        # Target distribution at the latest position (next byte).
        target_logits = out.byte_logits[0, -1, 0]  # [vocab]
        target_probs = _softmax_with_top_p(target_logits, temperature, top_p)

        # Draft proposals: walk the MTP head depth-wise, threading each
        # proposed byte into the next depth's target slot.
        proposals: list[int] = []
        proposal_probs: list[Tensor] = []
        h_last = patch_emb[0, -1]  # [d_model]
        h_cur = h_last.unsqueeze(0)  # [1, d_model]
        for d in range(mtp_depth):
            if d == 0:
                target_emb = torch.zeros_like(h_cur)
            else:
                target_emb = model.mtp.embed_for_targets(
                    torch.tensor([proposals[d - 1]], device=dev)
                )
            h_cur, draft_logits = model.mtp.layers[d](h_cur, target_emb)
            draft_logits = draft_logits[0]  # [vocab]
            draft_probs = _softmax_with_top_p(draft_logits, temperature, top_p)
            sample = torch.multinomial(
                draft_probs, num_samples=1, generator=generator
            ).item()
            proposals.append(int(sample))
            proposal_probs.append(draft_probs)

        # Accept/reject: only the first proposal is verified by `target_probs`
        # (next-byte distribution). Subsequent proposals are committed when
        # the head is accepted (degraded reference; production would re-verify).
        n_proposed += 1
        q0 = proposal_probs[0][proposals[0]].clamp_min(1e-12)
        p0 = target_probs[proposals[0]].clamp_min(1e-12)
        ratio = float((p0 / q0).clamp_max(1.0).item())
        u = torch.rand((), generator=generator).item()
        if u < ratio:
            n_accepted += 1
            bytes_so_far.append(proposals[0])
            for k in range(1, len(proposals)):
                if len(bytes_so_far) - len(prompt_bytes) >= n_new:
                    break
                bytes_so_far.append(proposals[k])
                n_proposed += 1
                n_accepted += 1
        else:
            corrected = (target_probs - proposal_probs[0]).clamp_min(0)
            if float(corrected.sum().item()) > 0:
                corrected = corrected / corrected.sum()
                fresh = torch.multinomial(
                    corrected, num_samples=1, generator=generator
                ).item()
            else:
                fresh = byte_sampler(
                    target_logits,
                    temperature=temperature,
                    top_p=top_p,
                    generator=generator,
                )
            bytes_so_far.append(int(fresh))

    rate = (n_accepted / n_proposed) if n_proposed > 0 else 0.0
    return bytes(bytes_so_far[len(prompt_bytes):]), rate


def _softmax_with_top_p(logits: Tensor, temperature: float, top_p: float) -> Tensor:
    """Apply temperature + top-p to `logits`, returning a probability vector."""
    if temperature <= 0:
        out = torch.zeros_like(logits)
        out[torch.argmax(logits)] = 1.0
        return out
    scaled = logits / max(temperature, 1.0e-6)
    probs = torch.softmax(scaled, dim=-1)
    if top_p is None or top_p >= 1.0:
        return probs
    sorted_probs, sorted_idx = torch.sort(probs, descending=True)
    cum = torch.cumsum(sorted_probs, dim=-1)
    keep = torch.zeros_like(cum, dtype=torch.bool)
    keep[..., 1:] = cum[..., :-1] <= top_p
    keep[..., 0] = True
    masked = torch.zeros_like(probs)
    masked[sorted_idx[keep]] = sorted_probs[keep]
    s = masked.sum()
    if float(s.item()) <= 0:
        return probs  # fallback
    return masked / s
